#! /bin/bash

ARDLIB=/home/pi/arduino-1.8.10

ARDTTY_PATTERN="tty(USB|ACM)"

if [ $# -eq 0 ]; then
 echo "Use args install, compile, upload, upload_loop, attach, update, listDevices, listCommands, install"
fi

if [ "$1" = "cua" ] ; then
 $0 compile && $0 upload $2 && $0 attach $2
fi

if [ "$1" = "install" ]; then
 command -v inotifywait > /dev/null || sudo apt-get install inotify-tools
 command -v screen > /dev/null || sudo apt-get install screen
 command -v cu > /dev/null || sudo apt-get install cu
#sudo apt-get  install avahi-daemon
fi

if [ "$1" = "compile" ]; then
 echo "Compiling Plummet"
 mkdir -p build
 ${ARDLIB}/arduino-builder -hardware ${ARDLIB}/hardware -tools ${ARDLIB}/hardware/tools/avr -tools ${ARDLIB}/tools-builder -libraries ${ARDLIB}/libraries -libraries Libraries -fqbn arduino:avr:uno -prefs=compiler.path=${ARDLIB}/hardware/tools/avr/bin/ -prefs=tools.ctags.path=${ARDLIB}/tools-builder/ctags/5.8-arduino11 -build-path build Plummet.ino 
 exit $? 
fi

if [ "$1" = "upload" ]; then
 echo "Uploading Plummet to ${2:-all connected devices}"
 for ard in $($0 listDevices $2); do
   echo "uploading to $ard"
   screen -R -S ${ard} -X quit
   ${ARDLIB}/hardware/tools/avr/bin/avrdude -C${ARDLIB}/hardware/tools/avr/etc/avrdude.conf -patmega328p -carduino -P/dev/${ard} -b115200 -Uflash:w:build/Plummet.ino.hex:i  &
 done
 wait
fi

if [ "$1" = "upload_loop" ]; then
 $0 upload $2
 echo "Continuesly uploading to any arduino that will be attached (Press Ctrl-C to stop)"
 inotifywait -m /dev -e create -e moved_to |
    while read path action ard; do
        if [[ $ard =~ $ARDTTY_PATTERN ]]; then # && [ $action = "CREATE" ]; then
           echo "New arduino connection detected ($ard)"
           $0 upload $ard
        fi
    done
fi

if [ "$1" = "update" ]; then
 echo Updating app from the internet
 git pull
 exit $?
fi

if [ "$1" = "listCommands" ]; then
 cat Plummet.ino | grep "case '" | sed s/case\ \'//g | sed s_\':\ //_:_g | awk '{printf "%s\r\n", $0} END {printf "  <Ctrl+A+D>: Detach\r\n"}'
fi

if [ "$1" = "attach_old" ]; then
 ard=$($0 listDevices $2| tail -1)
 if [ "$ard" == "" ]; then
   echo "No device matched attached. Following are the devices connected:"
   $0 listDevices
   exit 1
 fi 
 echo "Connecting to ${ard}:"

 $0 listCommands > $(cat /tmp/screen${ard})

 stty -F /dev/${ard} cs8 38400 ignbrk -brkint -icrnl -imaxbel -opost -ocrnl -onlret -isig -icanon -iexten -echo -echoe -echok -echoctl -echoke noflsh -ixon -crtscts
 screen -R -S ${ard} /dev/${ard} 9600

 #screen -R -S ${ard} bash -c 'tty > /tmp/screen${ard}; '$0' listCommands; cu -l /dev/'${ard}' -s 38400'
 #screen -R -S ${ard} bash -c 'tty > /tmp/screen${ard}; '$0' listCommands; tail -f /dev/'${ard}' &; cat > /dev/'${ard}
 # ~. to quit CU process
fi

if [ "$1" = "attach" ]; then
 while [ $(screen -ls | grep '(' | wc -l) -gt 0 ]; do screen -S $(screen -ls | grep '(' | head -1 | cut -d. -f 1) -X kill; sleep 0.1; done
 echo > /tmp/.screens
 isFirst=1
 for ard in $($0 listDevices $2); do
   stty -F /dev/${ard} cs8 38400 ignbrk -brkint -icrnl -imaxbel -opost -ocrnl -onlret -isig -icanon -iexten -echo -echoe -echok -echoctl -echoke noflsh -ixon -crtscts
   if [ "$isFirst" = "0" ]; then
      echo split >> /tmp/.screens
      echo focus >> /tmp/.screens
   fi
   echo screen /dev/${ard} >> /tmp/.screens
   if [ "$isFirst" = "1" ]; then
      echo split -v >> /tmp/.screens
      echo focus >> /tmp/.screens
      echo screen bash -c '"' $0 listCommands ';' exec bash  '"' >> /tmp/.screens
      echo focus prev >> /tmp/.screens
   fi
   isFirst=0
 done;
 echo "hardstatus alwayslastline" >> /tmp/.screens
 echo "hardstatus string 'Type <CTRL-A>+TAB to switch a tab. Type <CTRL-a>+d to detach (quit)'" >> /tmp/.screens
 screen -c /tmp/.screens

 #screen -R -S ${ard} bash -c 'tty > /tmp/screen${ard}; '$0' listCommands; cu -l /dev/'${ard}' -s 38400'
 #screen -R -S ${ard} bash -c 'tty > /tmp/screen${ard}; '$0' listCommands; tail -f /dev/'${ard}' &; cat > /dev/'${ard}
 # ~. to quit CU process
fi

if [ "$1" = "kill" ]; then
 for ard in $($0 listDevices $2); do
    echo "Killing connection to ${ard}"
    screen -R -S ${ard} -X quit
 done
fi

if [ "$1" = "listDevices" ]; then
 find /dev/ -type c -regextype "posix-extended" -iregex '/dev/('${2}'|'${ARDTTY_PATTERN}${2}'.*)' | cut -c 6- 
fi



